// SPDX-FileCopyrightText: 2023-2026 The EDDIE Developers <eddie.developers@fh-hagenberg.at>
// SPDX-License-Identifier: Apache-2.0

package energy.eddie.regionconnector.at.api;


import energy.eddie.api.agnostic.data.needs.EnergyDirection;
import energy.eddie.api.agnostic.process.model.PermissionRequest;
import energy.eddie.regionconnector.at.eda.requests.restricted.enums.AllowedGranularity;

import java.util.Optional;

public interface AtPermissionRequest extends PermissionRequest {
    /**
     * The CM Request ID of this permission request.
     *
     * @return cmRequestId
     */
    String cmRequestId();

    /**
     * In austria every conversation with the permission administrator requires a conversation id. For a permission
     * request this id is generated by eddie.
     *
     * @return conversationId
     */
    String conversationId();

    /**
     * In Austria every permission request is associated with exactly one metering point. When the request is sent
     * without a metering point id, the user is asked to select a metering point in his DSO web portal. So it can be
     * empty in the beginning, but it will always be set once the request has been accepted.
     * This will always be present if the {@link #dataNeedId()} is a {@link energy.eddie.dataneeds.needs.CESUJoinRequestDataNeed}.
     *
     * @return meteringPointId
     */
    Optional<String> meteringPointId();

    /**
     * EDA will generate a consentId for a permission request after it was accepted. So this ID is only available after
     * accepting the permission request.
     *
     * @return consentId
     */
    Optional<String> consentId();

    /**
     * Message that was sent by EDA in their CCMO messages.
     *
     * @return message
     */
    String message();

    /**
     * The granularity of the energy data that is requested by this permission request.
     *
     * @return granularity
     */
    AllowedGranularity granularity();

    /**
     * The participation factor of a final customer in a CESU.
     * Only present if this permission request has a {@link energy.eddie.dataneeds.needs.CESUJoinRequestDataNeed}.
     *
     * @return Participation factor in a CESU.
     */
    Optional<Integer> participationFactor();

    /**
     * Returns the EnergyDirection of the {@link #meteringPointId()}.
     * Similar to the {@link #participationFactor()} this is only present if the data need is a {@link energy.eddie.dataneeds.needs.CESUJoinRequestDataNeed}.
     *
     * @return EnergyDirection of the metering point ID.
     */
    Optional<EnergyDirection> energyDirection();
}
